use std::fs;
use std::path::Path;

/// Brain file names within .brain/
const BRAIN_FILES: &[&str] = &[
    "index.md",
    "context.md",
    "architecture.md",
    "memory.md",
    "changelog.md",
    "roadmap.md",
    "decisions.md",
    "prompt.md",
    "tree.md",
    "readme.md",
    "tasks.md",
];

/// Knowledge sub-files within .brain/knowledge/
const KNOWLEDGE_FILES: &[&str] = &[
    "modules.md",
    "functions.md",
    "api.md",
    "database.md",
    "models.md",
    "services.md",
];

/// Initialize the .brain/ directory structure with seed files.
pub fn init_brain(root: &Path) -> Result<(), String> {
    let brain_dir = root.join(".brain");
    let knowledge_dir = brain_dir.join("knowledge");

    // Create directories
    fs::create_dir_all(&knowledge_dir)
        .map_err(|e| format!("Failed to create .brain/ directory: {}", e))?;

    // Create brain files (only if they don't exist)
    for file in BRAIN_FILES {
        let path = brain_dir.join(file);
        if !path.exists() {
            let seed = seed_content(file);
            fs::write(&path, &seed)
                .map_err(|e| format!("Failed to create .brain/{}: {}", file, e))?;
        }
    }

    // Create knowledge files (only if they don't exist)
    for file in KNOWLEDGE_FILES {
        let path = knowledge_dir.join(file);
        if !path.exists() {
            let seed = format!(
                "# {}\n\n> Auto-generated by TreeC Neural Link\n\n",
                title_from_filename(file)
            );
            fs::write(&path, &seed)
                .map_err(|e| format!("Failed to create .brain/knowledge/{}: {}", file, e))?;
        }
    }

    Ok(())
}

/// Update the tree.md file with the latest Tree.md content.
pub fn update_tree(root: &Path, tree_content: &str) -> Result<(), String> {
    let brain_tree = root.join(".brain").join("tree.md");
    fs::write(&brain_tree, tree_content)
        .map_err(|e| format!("Failed to write .brain/tree.md: {}", e))
}

/// Write AI-generated content to a specific brain file.
pub fn update_brain_file(root: &Path, filename: &str, content: &str) -> Result<(), String> {
    let path = root.join(".brain").join(filename);

    // Ensure parent directory exists
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create directory: {}", e))?;
    }

    fs::write(&path, content).map_err(|e| format!("Failed to write .brain/{}: {}", filename, e))
}

/// Seed content for each brain file.
fn seed_content(filename: &str) -> String {
    match filename {
        "index.md" => r#"# 🧠 Project Brain — Index

> Auto-generated by TreeC Neural Link

## Navigation

- [[context]] — Project overview
- [[architecture]] — System architecture
- [[memory]] — Long-term memory
- [[changelog]] — Change tracking
- [[roadmap]] — Future plans
- [[decisions]] — Technical decisions
- [[prompt]] — AI agent rules
- [[tree]] — File structure
- [[readme]] — Project README
- [[tasks]] — Task list

## Knowledge Base

- [[knowledge/modules]] — Module documentation
- [[knowledge/functions]] — Function reference
- [[knowledge/api]] — API documentation
- [[knowledge/database]] — Database schema
- [[knowledge/models]] — Data models
- [[knowledge/services]] — Service documentation
"#.to_string(),

        "prompt.md" => AGENT_PROMPT.to_string(),

        "memory.md" => format!(
            "# 🧠 Memory\n\n> Long-term project memory. Never delete entries, only append.\n\n## Memory Entry - {}\n- Brain initialized by TreeC Neural Link\n- Initial project scan completed\n",
            chrono::Local::now().format("%Y-%m-%d")
        ),

        "changelog.md" => format!(
            "# 📋 Changelog\n\n## Change - {}\n- File modified: .brain/*\n- Description: Brain initialized by TreeC Neural Link\n- Reason: First neural link execution\n- Risk: None\n- Status: Complete\n",
            chrono::Local::now().format("%Y-%m-%d")
        ),

        "decisions.md" => "# 🔀 Technical Decisions\n\n> Register all technical decisions here.\n\n".to_string(),

        "roadmap.md" => "# 🗺️ Roadmap\n\n> Future features and improvements.\n\n".to_string(),

        "tasks.md" => "# ✅ Tasks\n\n> Active task list.\n\n".to_string(),

        "context.md" => "# 📄 Context\n\n> Project overview — will be populated by Neural Link AI.\n\n".to_string(),

        "architecture.md" => "# 🏗️ Architecture\n\n> System architecture — will be populated by Neural Link AI.\n\n".to_string(),

        "readme.md" => "# 📖 README\n\n> AI-generated README — will be populated by Neural Link AI.\n\n".to_string(),

        "tree.md" => "# 🌳 Tree\n\n> File structure — will be updated by TreeC.\n\n".to_string(),

        _ => format!("# {}\n\n> Auto-generated by TreeC Neural Link\n\n", title_from_filename(filename)),
    }
}

/// Convert filename to a readable title.
fn title_from_filename(filename: &str) -> String {
    filename
        .trim_end_matches(".md")
        .split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

// ═══════════════════════════════════════════════════════════════════
// Agent Prompt — Hardcoded from spec
// ═══════════════════════════════════════════════════════════════════

const AGENT_PROMPT: &str = r#"# TreeC Neural Brain — Agent Prompt

## Identity
You are an AI software engineer integrated into a project through TreeC Neural Link.
Your job is to understand the entire project, maintain memory, document decisions, and safely improve the codebase.

You do not act like a chatbot.
You act like a persistent software agent with memory and project awareness.

---

# Core Rules

Before performing ANY code modification, you MUST:

1. Read index.md
2. Read context.md
3. Read architecture.md
4. Read memory.md
5. Read roadmap.md
6. Read decisions.md
7. Read changelog.md

Only after understanding the project context you may proceed.

---

# Memory System Rules

## memory.md
This file is the long-term memory of the project.

You must append new entries when:
- A new feature is added
- Architecture changes
- Important refactor happens
- Bugs are fixed
- New dependencies are added
- Important insights are discovered

Memory entries format:

## Memory Entry - YYYY-MM-DD
- What changed
- Why it changed
- Impact on system
- Important notes

Never delete old memory entries. Only append.

---

# Changelog Rules

## changelog.md
Every code modification must be registered.

Format:

## Change - YYYY-MM-DD
- File modified:
- Description:
- Reason:
- Risk:
- Status:

You must update changelog BEFORE finishing a task.

---

# Decisions Log

## decisions.md
Register all technical decisions.

Format:

## Decision
Date:
Decision:
Reason:
Alternatives considered:
Impact:

---

# Roadmap Rules

## roadmap.md
You may add: features, improvements, refactors, performance & security improvements.

Format:

## Feature
Description:
Priority:
Difficulty:
Impact:

---

# Code Modification Rules

Before modifying code:
1. Understand architecture
2. Check roadmap
3. Check memory
4. Check previous decisions
5. Evaluate impact
6. Register planned change in changelog
7. Modify code
8. Update memory
9. Update documentation
10. Update context if necessary

---

# Behavior Rules

You should:
- Prefer refactoring over rewriting
- Prefer simple solutions
- Avoid unnecessary dependencies
- Maintain consistent architecture
- Document everything
- Think before coding
- Keep the project organized
- Improve documentation
- Suggest improvements
- Identify technical debt, performance issues, and security issues

---

# Goal

Your goal is to:
- Understand the project
- Maintain project memory
- Document architecture
- Track decisions and changes
- Improve the system
- Help evolve the project
- Act like a persistent engineering agent

You are the project's second brain.
"#;
